In [42]:
import pybullet
import gym
import numpy as np
import matplotlib.pyplot as plt
import pybullet_data
import math
import rrtstar
import mpc
import torch

In [ ]:
#!git clone https://github.com/ROBOTIS-GIT/turtlebot3.git

In [39]:
# Initializing pybullet
physicsClient = pybullet.connect(pybullet.GUI)
pybullet.setAdditionalSearchPath(pybullet_data.getDataPath())
pybullet.setGravity(0,0,-9.8)

# Loading chessgrid plane
planeID = pybullet.loadURDF('plane.urdf')
chess_grid = pybullet.loadTexture('checker_huge.gif')
pybullet.changeVisualShape(planeID, -1, textureUniqueId=chess_grid)




# Creating robots
player = pybullet.loadURDF('turtlebot3/turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf.xacro', [0.25,0.25,0], pybullet.getQuaternionFromEuler([0,0,0]))

start = (0.25,0.25)

static = []

static.append(pybullet.loadURDF('turtlebot3/turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf.xacro', [0.75,0.25,0], pybullet.getQuaternionFromEuler([0,0,math.pi])))
static.append(pybullet.loadURDF('turtlebot3/turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf.xacro', [0.75,0.75,0], pybullet.getQuaternionFromEuler([0,0,math.pi])))
static.append(pybullet.loadURDF('turtlebot3/turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf.xacro', [0.75,-0.25,0], pybullet.getQuaternionFromEuler([0,0,math.pi])))
static.append(pybullet.loadURDF('turtlebot3/turtlebot3_description/urdf/turtlebot3_waffle_pi.urdf.xacro', [1.25,0.75,0], pybullet.getQuaternionFromEuler([0,0,math.pi])))
target = static[3]

goal = (1.25, 0.75)

# For milestone 2 only - setting all non-player targets to have no collision with player robot
# Doesn't work when dragging into each other but might still work?
pybullet.setCollisionFilterGroupMask(player, target, 0, 0)

for robot in static:
    pybullet.setCollisionFilterGroupMask(player, robot, 0, 0)

# Setting colors to distinguish robots. BLUE for player, GREEN for obstacle, RED for target
pybullet.changeVisualShape(player, 0, rgbaColor=[0,0,1,1])
for robot in static:
    pybullet.changeVisualShape(robot, 0, rgbaColor=[0,1,0,1])
pybullet.changeVisualShape(target, 0, rgbaColor=[1,0,0,1])



# Setting up overhead camera
viewMatrix = pybullet.computeViewMatrix(
            cameraEyePosition=[0.75,0.25,3],
            cameraTargetPosition=[0.75,0.25,0],
            cameraUpVector=[0,1,0])

projectionMatrix = pybullet.computeProjectionMatrixFOV(
            fov=45.0,
            aspect=1.0,
            nearVal=0.1,
            farVal=3.1)

width, height, rgbImg, depthImg, segImg = pybullet.getCameraImage(width = 224, height = 224, viewMatrix=viewMatrix, projectionMatrix = projectionMatrix)

# Getting position and orientation
print(pybullet.getBasePositionAndOrientation(player))
print(pybullet.getBasePositionAndOrientation(static[0]))
print(pybullet.getBasePositionAndOrientation(static[1]))
print(pybullet.getBasePositionAndOrientation(static[2]))
print(pybullet.getBasePositionAndOrientation(target))


# Start simulation
pybullet.setRealTimeSimulation(1)

((0.25, 0.25, 0.0), (0.0, 0.0, 0.0, 1.0))
((0.75, 0.25, 0.0), (0.0, 0.0, 1.0, 6.123233995736766e-17))
((0.75, 0.75, 0.0), (0.0, 0.0, 1.0, 6.123233995736766e-17))
((0.75, -0.25, 0.0), (0.0, 0.0, 1.0, 6.123233995736766e-17))
((1.25, 0.75, 0.0), (0.0, 0.0, 1.0, 6.123233995736766e-17))


In [43]:
# RRT
samplingArea = [0.25, 1.25, -0.25, 0.75]
RRT = rrtstar.RRT(start, goal, [], samplingArea, 'rrtstar', 'rectangle', 2)
path = RRT.planning()

[0.25, 0.25, 0]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.505805412763662

[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048821033, 0.961998768729382]
[0. 0. 0.]
[1.0197257431289184, 0.26239299543043526, 1.8062801302924263]
[0. 0. 0.]
[1.25, 0.75, 0]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.77

[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048821033, 0.961998768729382]
[0. 0. 0.]
[1.0197257431289184, 0.26239299543043526, 1.8062801302924263]
[0. 0. 0.]
[1.25, 0.75, 0]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.6246581351945759, 0.014513152670132534, 3.6926864034829454]
[0. 0. 0.]
[0.3007021593379424, -0.10440439360856979, 3.2229138770920986]
[0. 0. 0.]
[0.8232693274933491, -0.05253715288763916, 5.419712626302902]
[0. 0. 0.]
[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.9207812685961987, -0.13053978

[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.127276701711411, -0.10562136951417533, 2.1914946187607716]
[0. 0. 0.]
[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048

[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789

[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.1666620880701

[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0.

[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[

[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294

[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.307388458

[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048821033, 0.961998768729382]
[0. 0. 0.]
[1.0197257431289184, 0.26239299543043526, 1.8062801302924263]
[0. 0. 0.]
[1.25, 0.75, 0]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.6246581351945759, 0.014513152670132534, 3.6926864034829454]
[0. 0. 0.]
[0.3007021593379424, -0.10440439360856979, 3.2229138770920986]
[0. 0. 0.]
[0.8232693274933491, -0.05253715288763916, 5.419712626302902]
[0. 0. 0.]
[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.162769518601982

[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[0.7495835328888519, 0.4256985555184891, 5.10698801698425]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.127276701711411, -0.10562136951417533, 2.1914946187607716]
[0. 0. 0.]
[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048821033, 0.961998768729382]
[0. 0. 0.]
[1.0197257431289184, 0.26239299543043526, 1.8062801302924263]
[0. 0. 0.]
[1.25, 0.75, 0]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.62465813519

[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.7870163475832763]
[0. 0. 0.]
[1.127276701711411, -0.10562136951417533, 2.1914946187607716]
[0. 0. 0.]
[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.

[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.5745201226488963,

[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659

[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[0.6473452470775615, 0.5028213849833693, 5.451993993042512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.6367331677443582, -0.16652394607157228, 4.0307189793604925]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0.

[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722

[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496

[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0.

[0. 0. 0.]
[1.1415890421984032, -0.03814324388892598, 2.4118018433128134]
[0. 0. 0.]
[0.4374115692684648, -0.11692128132704871, 5.367299956518642]
[0. 0. 0.]
[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[0.6473452470775615, 0.5028213849833693, 5.451993993042512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.6367331677443582, -0.16652394607157228, 4.0307189793604925]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232

[0.9570444947723953, 0.3067274734433544, 0.29659664731918306]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0

[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.6287889645700159, 0.6564576896758271, 2.3961164246302182]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.38764274309127167, 0.6127323300433447, 3.5422220475972126]
[0. 0. 0.]
[0.9570444947723953, 0.3067274734433544, 0.29659664731918306]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.4390843393606002, -0.037604737328531535, 2.002971

[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725,

[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.47679074281657546]
[0. 0. 0.]
[1.2323090793352747, -0.089863182780472, 3.9948141092835256]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7495835328888519, 0.4256985555184891, 5.10698801698425]


[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286

[0.7267880666159426, 0.031659832397682, 4.1602701624511305]
[0. 0. 0.]
[0.3081882908274268, 0.036305856914389034, 5.831508057728971]
[0. 0. 0.]
[0.6064544271093925, 0.30664906514075685, 5.785993701274605]
[0. 0. 0.]
[0.9405912474814083, 0.7430010048821033, 0.961998768729382]
[0. 0. 0.]
[1.0197257431289184, 0.26239299543043526, 1.8062801302924263]
[0. 0. 0.]
[1.25, 0.75, 0]
[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.6246581351945759, 0.014513152670132534, 3.6926864034829454]
[0. 0. 0.]
[0.3007021593379424, -0.10440439360856979, 3.2229138770920986]
[0. 0. 0.]
[0.8232693274933491, -0.05253715288763916, 5.419712626302902]
[0. 0. 0.]
[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535

[0.4374115692684648, -0.11692128132704871, 5.367299956518642]
[0. 0. 0.]
[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[0.6473452470775615, 0.5028213849833693, 5.451993993042512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.6367331677443582, -0.16652394607157228, 4.0307189793604925]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.6287889645700159, 0.6564576896758271, 2.3961164246302182]
[0

[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213

[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.47679074281657546]
[0. 0. 0.]
[1.2323090793352747, -0.089863182780472, 3.9948141092835256]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7495835328888519, 0.4256985555184891, 5.10698801698425]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.665914553829108

[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013514909500996652, 5.871879708751294]
[0. 0. 0.]
[1.1492352010054394, -0.013

[0.6473452470775615, 0.5028213849833693, 5.451993993042512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.6073765449322512]
[0. 0. 0.]
[0.6367331677443582, -0.16652394607157228, 4.0307189793604925]
[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.6287889645700159, 0.6564576896758271, 2.3961164246302182]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.38764274309127167, 0.6127323300433447, 3.5422220475972126]


[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.476790

[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130382721716]
[0. 0. 0.]
[0.7427572205399838, 0.40353256700933793, 1.0537130

[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.9303255907544661, 0.0927643746541037, 5.760784848172159]
[0. 0. 0.]
[0.930

[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316336539145]
[0. 0. 0.]
[0.4258556233819615, 0.18544566321809552, 2.9440316

[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683960226]
[0. 0. 0.]
[0.33885198957799934, 0.7396173752291342, 2.907176683

[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0.

[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.47679074281657546]
[0. 0. 0.]
[1.2323090793352747, -0.089863182780472, 3.9948141092835256]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651

[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0.

[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.9808503446603574]
[0. 0. 0.]
[0.66452949023024, 0.18198786341974194, 0.24587848577906402]
[0. 0. 0.]
[0.4467645942648564, 0.413264464866277, 0.16666208807010005]
[0. 0. 0.]
[0.4924281051513183, 0.04991820162060878, 3.1071189544450535]
[0. 0. 0.]
[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.47679074281657546]
[0. 0. 0.]
[1.2323090793352747, -0.089863182780472, 3.9948141092835256]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7495835328888519, 0.4256985555184891, 5.10698801698425]


[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.6287889645700159, 0.6564576896758271, 2.3961164246302182]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.38764274309127167, 0.6127323300433447, 3.5422220475972126]
[0. 0. 0.]
[0.9570444947723953, 0.3067274734433544, 0.29659664731918306]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.4390843393606002, -0.037604737328531535, 2.002971357693936]
[0. 0. 0.]
[0.5677658427326981, 0.25967920885424467, 0.7888329664707574]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.41701094892542945, 0.3151247782489257, 2.0394558222154053]
[0. 0. 0.]
[1.1705034940345582, -0.12339815727676884, 1.1448260367498706]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 

[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.0666682500779276,

[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530

[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.96209611955

[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735

[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640

[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626

[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586

[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[0.25, 0.25, 0]
[0. 0. 0.]
[0.30738845860818487, 0.5058054127636629, 3.5257876380570576]
[0. 0. 0.]
[0.5628446963165923, -0.1773334460303655, 0.3383704625048422]
[0. 0. 0.]
[1.0060097991304298, 0.3712747202576826, 0.

[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0. 0.]
[0.8867497936377905, 0.6611165673943684, 3.622206573967973]
[0. 0.

[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687, 1.9434703494599852]
[0. 0. 0.]
[0.9282337325126172, 0.12542763012324687

[0. 0. 0.]
[0.5745201226488963, 0.4047358123913358, 5.39064907256081]
[0. 0. 0.]
[0.8728418873770092, 0.667060196008717, 5.337437924205997]
[0. 0. 0.]
[1.1072087896756628, -0.14138002629555946, 4.652659154318711]
[0. 0. 0.]
[0.7555288867000552, 0.4527921704412441, 5.885678904998024]
[0. 0. 0.]
[0.6425707270237094, 0.11103251947847048, 2.626858816682424]
[0. 0. 0.]
[0.8434780727230266, -0.04326894108722801, 4.1035551780220665]
[0. 0. 0.]
[1.169716955188433, 0.10369214870373689, 1.0013311284337887]
[0. 0. 0.]
[0.7376561516535869, 0.16207599089827496, 0.6970232708692642]
[0. 0. 0.]
[0.6287889645700159, 0.6564576896758271, 2.3961164246302182]
[0. 0. 0.]
[0.2696802690258836, 0.6338149369483362, 1.9111133050529479]
[0. 0. 0.]
[0.38764274309127167, 0.6127323300433447, 3.5422220475972126]
[0. 0. 0.]
[0.9570444947723953, 0.3067274734433544, 0.29659664731918306]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.4390843393606002, -0.037604737328531535, 2.002971

[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0. 0. 0.]
[1.217012015120808, -0.1245895905113783, 3.3080591633515173]
[0.

[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712, 2.6483827773364146]
[0. 0. 0.]
[0.48567092833355474, 0.5441302670033712

[0. 0. 0.]
[0.38764274309127167, 0.6127323300433447, 3.5422220475972126]
[0. 0. 0.]
[0.9570444947723953, 0.3067274734433544, 0.29659664731918306]
[0. 0. 0.]
[0.9764377885279086, -0.065686279275607, 1.3001774304764107]
[0. 0. 0.]
[0.4390843393606002, -0.037604737328531535, 2.002971357693936]
[0. 0. 0.]
[0.5677658427326981, 0.25967920885424467, 0.7888329664707574]
[0. 0. 0.]
[0.8354390633396934, 0.5128272813184725, 0.14713572525017368]
[0. 0. 0.]
[0.41701094892542945, 0.3151247782489257, 2.0394558222154053]
[0. 0. 0.]
[1.1705034940345582, -0.12339815727676884, 1.1448260367498706]
[0. 0. 0.]
[1.1211252729103744, 0.5261825130167962, 0.18622286545504488]
[0. 0. 0.]
[0.5720538434624198, 0.444505264024293, 0.5282773303555448]
[0. 0. 0.]
[0.2790106007033397, -0.08240393585040107, 0.6609589944690767]
[0. 0. 0.]
[0.33634019299979234, 0.04726666329418072, 2.838988812511211]
[0. 0. 0.]
[1.1444665077883671, 0.6017089041191531, 5.2075638149494115]
[0. 0. 0.]
[0.3337979064844935, -0.03218467210546605

[0.4277053590075589, 0.5026971576980441, 3.9538854018763168]
[0. 0. 0.]
[0.36490672528587365, 0.5865661161270668, 0.20926213291346815]
[0. 0. 0.]
[0.32890219598402637, -0.07194178908887416, 4.313970057307489]
[0. 0. 0.]
[0.2847757495410407, 0.3290137140669116, 0.47679074281657546]
[0. 0. 0.]
[1.2323090793352747, -0.089863182780472, 3.9948141092835256]
[0. 0. 0.]
[0.7497330624869918, -0.18220541449294503, 0.9651905590455475]
[0. 0. 0.]
[0.7495835328888519, 0.4256985555184891, 5.10698801698425]
[0. 0. 0.]
[0.9196177933932018, -0.1742064844750003, 2.6659145538291087]
[0. 0. 0.]
[0.8331535881031463, -0.11887007551072615, 0.8870441612618497]
[0. 0. 0.]
[1.1415890421984032, -0.03814324388892598, 2.4118018433128134]
[0. 0. 0.]
[0.4374115692684648, -0.11692128132704871, 5.367299956518642]
[0. 0. 0.]
[1.246028145200119, 0.5371333829178103, 2.294396795162113]
[0. 0. 0.]
[0.6473452470775615, 0.5028213849833693, 5.451993993042512]
[0. 0. 0.]
[0.41087170300075504, 0.08519162892973398, 3.60737654493

[0. 0. 0.]
[0.7681594496054017, 0.7119228287012497, 5.773111196770995]
[0. 0. 0.]
[0.6246581351945759, 0.014513152670132534, 3.6926864034829454]
[0. 0. 0.]
[0.3007021593379424, -0.10440439360856979, 3.2229138770920986]
[0. 0. 0.]
[0.8232693274933491, -0.05253715288763916, 5.419712626302902]
[0. 0. 0.]
[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.7443

[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854, 0.7020512838203656, 3.21542261906323]
[0. 0. 0.]
[1.1529708061475854,

[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.18301198531020435, 0.8580776675103329]
[0. 0. 0.]
[0.6914142951743906, -0.183

[0.54157861107001, 0.14866736645038525, 2.3561841445067193]
[0. 0. 0.]
[0.5440813940035228, 0.28077582485074326, 6.025051834528461]
[0. 0. 0.]
[0.7597342362595815, 0.4343132899963068, 0.8010726029760312]
[0. 0. 0.]
[0.4367083402684825, -0.09936615287547801, 1.2216664756019764]
[0. 0. 0.]
[0.5761018586048304, 0.15924076830747835, 2.329795676090894]
[0. 0. 0.]
[0.3865093694836359, 0.049717698291993795, 1.9545883044973114]
[0. 0. 0.]
[1.0666682500779276, 0.420288609925049, 2.749598172414512]
[0. 0. 0.]
[1.196814208046507, 0.12024822690362791, 0.5629582530910526]
[0. 0. 0.]
[0.9620961195575648, -0.032394034689084084, 3.4353600415425087]
[0. 0. 0.]
[0.8210414881958649, 0.08573854161087735, 1.6300310254055606]
[0. 0. 0.]
[0.2700540118633872, 0.14698626649419388, 2.586689640209027]
[0. 0. 0.]
[0.9603233953244126, 0.5227583955484588, 4.2089788626323825]
[0. 0. 0.]
[0.7230008398125178, 0.06440948465389862, 0.5239586626761721]
[0. 0. 0.]
[1.0146569589895935, 0.30335021699555, 1.9915204231680392]

[0.6246581351945759, 0.014513152670132534, 3.6926864034829454]
[0. 0. 0.]
[0.3007021593379424, -0.10440439360856979, 3.2229138770920986]
[0. 0. 0.]
[0.8232693274933491, -0.05253715288763916, 5.419712626302902]
[0. 0. 0.]
[0.9767467543088669, 0.21025385896382942, 2.0639932059391723]
[0. 0. 0.]
[0.9207812685961987, -0.1305397869824826, 1.954825326590505]
[0. 0. 0.]
[0.4365123895446561, -0.13706735944806114, 2.5257443171425003]
[0. 0. 0.]
[0.8819490826542858, 0.1606422429226081, 6.245647128358687]
[0. 0. 0.]
[0.8844288193757872, 0.38825535630016983, 3.2667133540161513]
[0. 0. 0.]
[1.1627695186019822, 0.6593556126637353, 1.8738013829159441]
[0. 0. 0.]
[0.785554349555948, 0.03804882235193985, 0.17828521794499072]
[0. 0. 0.]
[1.0726264814246982, 0.2613818513238729, 1.09759571429714]
[0. 0. 0.]
[0.826694373379514, 0.4631270087773415, 4.262305095483498]
[0. 0. 0.]
[1.1330410943431952, -0.07875710174246497, 5.744306222789916]
[0. 0. 0.]
[0.5762161388378964, 0.5120497548865143, 3.980850344660357

[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052390378201]
[0. 0. 0.]
[0.30990346993334605, 0.04059498620589974, 2.886052

In [44]:
path = np.flip(path, 0)
print(path)


[[0.25       0.25       0.        ]
 [0.44676459 0.41326446 0.16666209]
 [1.25       0.75       0.        ]
 [1.25       0.75       0.        ]]


In [50]:
def applyAction(actions, orig_state):
    new_states = []
    for i in range(G):
        action_set = actions[i]
        for j in range(H):
            action = action_set[j]
            action_3d = [action[0], action[1], 0]
            pybullet.applyExternalForce(player, -1, action_3d, [0,0,0], pybullet.WORLD_FRAME)
        
        new_states.append(pybullet.getBasePositionAndOrientation(player))
        pybullet.resetBasePositionAndOrientation(player, orig_state[0], orig_state[1])
    return new_states
        

In [53]:
def getCost(states, target):
    target_pos = [target[0], target[1]]
    target_angle = target[2]
    costs = []
    for i in range(G):
        current = states[i]
        current_pos = current[0]
        current_angle = pybullet.getEulerFromQuaternion(current[1])[2]
        # Double check above. Based on angle used for initial setting position
        cost = math.sqrt(((current_pos[0] - target_pos[0]) ** 2) + ((current_pos[1] - target_pos[1]) ** 2))
        cost += abs(current_angle - target_angle)
        costs.append(cost)
    return costs

In [54]:
H = 5
G = 1000
T = 500
K = 100

def cem(path):
    pybullet.setRealTimeSimulation(0)
    for i in range(len(path) - 1):
        initial_actions = np.random.normal(0,1,(G,H,2))
        state = pybullet.getBasePositionAndOrientation(player)
        for t in range(T):
            new_states = applyAction(initial_actions, state)
            costs = getCost(new_states, path[i + 1])
            print(initial_actions)
            print(costs)
            sorted_actions = [act for _,act in sorted(zip(costs, initial_actions))]
            new_mean = np.mean(sorted_actions[:K])
            new_std = np.std(sorted_actions[:K])
            new_actions = np.random.normal(new_mean, new_std, (G,H,2))
            initial_actions = np.concatenate(sorted_actions[:K], new_actions)
            
        best_action = initial_actions[0][0] # Because no horizon length
        action = [best_action[0], best_action[1], 0]
        pybullet.applyExternalForce(player, -1, action, [0,0,0], pybullet.WORLD_FRAME)
    
            
            


In [55]:
cem(path)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# MPC
horizon_length = 5
opt_iters = 10
samples = 100
top_samples = 10

device = torch.device('cpu')

In [ ]:
def reward(action):
    

In [ ]:
import test_energy
env = test_energy.FuncMinGTEnv(1, 2, )
CEM = mpc.CEM(horizon_length, opt_iters, samples, top_samples,env,device)

In [38]:
pybullet.disconnect()